// -*- Mode: Go; indent-tabs-mode: t -*-
// local version

// AUTOMATICALLY GENERATED BY mlpa muc20 image builder

/*
 * Copyright (C) 2014,2015,2017 ML!PA GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package constants

const (
	BaseUrlSnapcraftDashboard        = "https://app-snapstore-api-st02-dev.azurewebsites.net/"
	BaseUrlSnapcraftDashboardStaging = "https://app-snapstore-api-st02-dev.azurewebsites.net/"
	BaseUrlSnapcraftApi              = "https://app-snapstore-api-st02-dev.azurewebsites.net/"
	BaseUrlSnapcraftStagingApi       = "https://app-snapstore-api-st02-dev.azurewebsites.net/"
	BaseUrlSnapcraftApiV2            = "https://app-snapstore-api-st02-dev.azurewebsites.net/v2/"
	BaseUrlSnapcraftStagingApiV2     = "https://app-snapstore-api-st02-dev.azurewebsites.net/v2/"
	AuthLocation                     = "app-snapstore-api-st02-dev.azurewebsites.net"
	AuthLocationStaging              = "app-snapstore-api-st02-dev.azurewebsites.net"

	AccountId = "mlpa"

	EncodedRepairRootAccountKeyPublicKeySha3 = "edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h"
	EncodedRepairRootAccountKey              = `type: account-key
authority-id: mlpa
public-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h
account-id: mlpa
name: root
since: 2022-11-29T12:47:20Z
body-length: 717
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcbBTQRWhcGAARAAv51tX3HcHjMYIh/o6oAOy/dlrS38F8t2/fLnhzb3UaIPEqT5g8f+fAf0r307
/6ROzqQRbtf5uM8pPUwawRIpvrL5F6TFkSfKgzeKQeBEpAij+sjRPGfIPoARBbXFG4Z7VBZdZUyD
qIRnsP/adwBbCJ0iSX29AqT/veLOg8VYUEaRmUf1TsAnTttHqBQzvptz9vpSTj27fLTI3vcNCDYg
VUNMUmd3Sds0ynnjtlc5TuaJrvs4avq4tEL36JvJjfnyha1G4WXGTXTfrT1ZWGMQEJMuQZ2tfQdj
65uhf4rXLZmT2cumWp5Tr2NFsPDoCNXspcbzu8uT/19I1TL72LqsqxBpJbR0FPtkSlfeLz1mwepd
t7apWWMmZzebgPxNXRDr+PHE69vV1RpXr0e9tsirzdY5jmMoqd4Pjp5rOU5BUq5mbn4oX7CW7pZW
dgH+uFodF4g5mNxUciSAl7QVCVjdFNvpQkhIcS8o1K3BDJawIkPSYrBq5JpDHKGe4Fxtr6DPIeXh
3ekb/TK0igFeFq2Ge42Txmjk+YK80NHduYpTRRvNIGuYMEeSXKyt26LHNEWBMQZzYf8YXeAtuNg8
ejp3y3pLqfT2dUQdKA81drEMun31PoEep0P9jAYMBvYjUwKkbaOMerCqRIUGBv+zqzBDwzo049na
xJEd7t2R6nbANysAEQEAAQ==

AcLBUgQAAQoABgUCY4X/WAAAZecQAEpLDto9UXXJ5iQu5czQJ/LEJVvycF2zsSzjZE2HItFqzHmZ
rbqbUfoja994FWToRhBbAacye5IoHDMaEzq/cAOmGbVrI3pEa/YEnXlJXR+1A7LMMgTdVJwUKfnx
FW7oP98gb8CO0m8CnX5twct5EZku4a20jOunT9UDY58t6bKwSL8K/zGnpKMYEPk0hMe3lxroC1vz
nFITYxLoawQGGNiLW3jfc2NvTLTjt2/XgN1EI8K5GZoIcIsotXUCQ33kH5LmDHm0YsjkkTJbVrcN
6ugNub/O82pe95mlrgAxcsesjqLjCLwlMKLTtQCazXzRmPqBqB5jkNXO0gv9oSjoDuHxWgnH8YcH
hcv/RxGeU6dCu14aSGHb1SIqkVRtRBT7W0fg5lV86rl/XCzix4uqzF7Ew16wxJb0xhBs9JDYtiVm
fbFpB9iXEvD7yLzEMvRejKzs74cYSZTH6ZcSRYQfT1nU1CBT3+KuOypnqdp3/pAz0iy3E5Y1YT/i
7vDNu++Kq51RCyoNIOxSmUPvm2CfPfuk8PWeAo6MJdLe8Vwuqs6v7cC23U0HIFi4jz+WIj/0jFDr
/DSPCybc5tHgK7m0RVvoJ3TbpV8b9pcc8KEWersALy3Pf+mHPF2uF3edFP2ID0/3tY7OMAwLUtJ8
LwAr1Gi4GyBaujiuXM7FvPChriEj
`

	EncodedStagingRepairRootAccountKey = `type: account-key
authority-id: mlpa
public-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h
account-id: mlpa
name: root
since: 2022-11-29T12:47:20Z
body-length: 717
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcbBTQRWhcGAARAAv51tX3HcHjMYIh/o6oAOy/dlrS38F8t2/fLnhzb3UaIPEqT5g8f+fAf0r307
/6ROzqQRbtf5uM8pPUwawRIpvrL5F6TFkSfKgzeKQeBEpAij+sjRPGfIPoARBbXFG4Z7VBZdZUyD
qIRnsP/adwBbCJ0iSX29AqT/veLOg8VYUEaRmUf1TsAnTttHqBQzvptz9vpSTj27fLTI3vcNCDYg
VUNMUmd3Sds0ynnjtlc5TuaJrvs4avq4tEL36JvJjfnyha1G4WXGTXTfrT1ZWGMQEJMuQZ2tfQdj
65uhf4rXLZmT2cumWp5Tr2NFsPDoCNXspcbzu8uT/19I1TL72LqsqxBpJbR0FPtkSlfeLz1mwepd
t7apWWMmZzebgPxNXRDr+PHE69vV1RpXr0e9tsirzdY5jmMoqd4Pjp5rOU5BUq5mbn4oX7CW7pZW
dgH+uFodF4g5mNxUciSAl7QVCVjdFNvpQkhIcS8o1K3BDJawIkPSYrBq5JpDHKGe4Fxtr6DPIeXh
3ekb/TK0igFeFq2Ge42Txmjk+YK80NHduYpTRRvNIGuYMEeSXKyt26LHNEWBMQZzYf8YXeAtuNg8
ejp3y3pLqfT2dUQdKA81drEMun31PoEep0P9jAYMBvYjUwKkbaOMerCqRIUGBv+zqzBDwzo049na
xJEd7t2R6nbANysAEQEAAQ==

AcLBUgQAAQoABgUCY4X/WAAAZecQAEpLDto9UXXJ5iQu5czQJ/LEJVvycF2zsSzjZE2HItFqzHmZ
rbqbUfoja994FWToRhBbAacye5IoHDMaEzq/cAOmGbVrI3pEa/YEnXlJXR+1A7LMMgTdVJwUKfnx
FW7oP98gb8CO0m8CnX5twct5EZku4a20jOunT9UDY58t6bKwSL8K/zGnpKMYEPk0hMe3lxroC1vz
nFITYxLoawQGGNiLW3jfc2NvTLTjt2/XgN1EI8K5GZoIcIsotXUCQ33kH5LmDHm0YsjkkTJbVrcN
6ugNub/O82pe95mlrgAxcsesjqLjCLwlMKLTtQCazXzRmPqBqB5jkNXO0gv9oSjoDuHxWgnH8YcH
hcv/RxGeU6dCu14aSGHb1SIqkVRtRBT7W0fg5lV86rl/XCzix4uqzF7Ew16wxJb0xhBs9JDYtiVm
fbFpB9iXEvD7yLzEMvRejKzs74cYSZTH6ZcSRYQfT1nU1CBT3+KuOypnqdp3/pAz0iy3E5Y1YT/i
7vDNu++Kq51RCyoNIOxSmUPvm2CfPfuk8PWeAo6MJdLe8Vwuqs6v7cC23U0HIFi4jz+WIj/0jFDr
/DSPCybc5tHgK7m0RVvoJ3TbpV8b9pcc8KEWersALy3Pf+mHPF2uF3edFP2ID0/3tY7OMAwLUtJ8
LwAr1Gi4GyBaujiuXM7FvPChriEj
`

	EncodedCanonicalAccountSignKeySha3 = "edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h"
	EncodedCanonicalAccount            = `type: account
authority-id: mlpa
account-id: mlpa
display-name: mlpa
timestamp: 2023-02-08T12:51:16Z
username: mlpa
validation: certified
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcLBUgQAAQoABgUCY+OaxAAAgkkQALZjXtSmYr4lNv8Y81eaeL8uAi2zcpCDXRxkWQc01iYcW11R
iZ7PceSUs+zppCqSJa/NloqtqEeh6GozQYCme7N6UP1vUozSxHf0Ic4sYnCBXbGdC44KqGNOtXXV
XI9+oAZsgezUq1vyx+cYoX7nwJZYV41vZM3vGXftDOYohz2mnWG8nnBq+A5H7hDu4a2pha1kEO+H
k2jL5+mMyM+Pw+WB9HsuUFEuT9sXduuE98hSofCi+tRXHRlrr7tL6EcTx3pp5QB22sOr+YY+dbJX
Cf4hy7naLch8HRY2ovKDEpo+E1mKJ467J9X0HQUqo1FPxYj7MRBErV3+tumgnxBZQYCdG44xCDht
8AP/loqCNwfhEmAtKsWqW9XGLVqvMkvLoD2W7ldTxt6BuS6ZKF/pTDM09NWvQgWbxB/A0vOj+lUC
a/JKGqzfB1zJL2opFfEQO1WND36PF5nUErP/Mug3xENfGm2Y/34/1h06FuUX6El2lAARoDsy5xdL
n8dTA4JAmKY7Rz7Bfo/HytoNHQvc8ifxNbyxdUD5p2RweMMoMLeBao4xbmxlNfKOB4UeDnpFJR5T
wtdgiqsbdjorK/5qtdJXVSNf+mbkdGW6MNq579yjKjocrctjfO1Mfe8A4arXzQDn20metotrpl9s
s+3X5WuUiMdNbCiORoCAml6rT3QU


type: account
authority-id: mlpa
account-id: knorr
display-name: knorr
timestamp: 2023-02-16T14:57:30Z
username: knorr
validation: certified
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcLBUgQAAQoABgUCY+5EWgAATUkQAJptKSqOnuUNpRxFXhot418pn5t9LNa98dNCSs+XpkMs4W/B
ZtCVi4oQi7WerOh9tuKYciNA+dtv6MJbGagQxwZ5eT+hyxPuWpizPYfi8UmlEnhU4i2xPdSm4xCP
RN2b8mkITKi2dbmVmE9cl/JSkL58irCIazp7mEKRBQki9jv/QQZ5EGVrXXASlaqlq/zZThoLc2w7
qmFJTWtH3kbMMLHQ0HdqZ4fpMs8WiZ+qwEp8G7By4UDiQjmR6ucaRqp6SWfmwTL8eNWm5QGjSVeQ
NM+8LRFp/3Sf7i9y4d+cekuA0gdc5lZ6ZrJH59AKqjIEgIswSY1st+CrveIhRpJtyRb1t9SeLTND
ozmGiY10M9HId2QA4/pIvneZBFAzTbT4eQ9NnAko4Cg78n4BPA7bwOKSWnkNrEnWWaX8SpaR45h7
SqyXvjv1FpuwLvC10/vaYisr2KZ7fivK5THl+H+stFv2UZbWnuzjpWWqW28Y50Zmxrp9NA8RkZYe
ZOJPv1IpPEU86ecIlM5MPvviBvi1g6UON5zVdfrL0h9fjmjIZnIILNw8MPV7v5MSQJxxe62iwDzF
NLVt79RwDxNrSgRetDvj/9tJnJLF0xXYCjOCPSGg8YnSlexaow5KvsyHa2SrZk9smf6QWrLxyFZg
gVO/1zdQ6xa1X4e0l3CuBQWrFXDd
`

	EncodedCanonicalRootAccountKey = `type: account-key
authority-id: mlpa
public-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h
account-id: mlpa
name: root
since: 2022-11-29T12:47:20Z
body-length: 717
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcbBTQRWhcGAARAAv51tX3HcHjMYIh/o6oAOy/dlrS38F8t2/fLnhzb3UaIPEqT5g8f+fAf0r307
/6ROzqQRbtf5uM8pPUwawRIpvrL5F6TFkSfKgzeKQeBEpAij+sjRPGfIPoARBbXFG4Z7VBZdZUyD
qIRnsP/adwBbCJ0iSX29AqT/veLOg8VYUEaRmUf1TsAnTttHqBQzvptz9vpSTj27fLTI3vcNCDYg
VUNMUmd3Sds0ynnjtlc5TuaJrvs4avq4tEL36JvJjfnyha1G4WXGTXTfrT1ZWGMQEJMuQZ2tfQdj
65uhf4rXLZmT2cumWp5Tr2NFsPDoCNXspcbzu8uT/19I1TL72LqsqxBpJbR0FPtkSlfeLz1mwepd
t7apWWMmZzebgPxNXRDr+PHE69vV1RpXr0e9tsirzdY5jmMoqd4Pjp5rOU5BUq5mbn4oX7CW7pZW
dgH+uFodF4g5mNxUciSAl7QVCVjdFNvpQkhIcS8o1K3BDJawIkPSYrBq5JpDHKGe4Fxtr6DPIeXh
3ekb/TK0igFeFq2Ge42Txmjk+YK80NHduYpTRRvNIGuYMEeSXKyt26LHNEWBMQZzYf8YXeAtuNg8
ejp3y3pLqfT2dUQdKA81drEMun31PoEep0P9jAYMBvYjUwKkbaOMerCqRIUGBv+zqzBDwzo049na
xJEd7t2R6nbANysAEQEAAQ==

AcLBUgQAAQoABgUCY4X/WAAAZecQAEpLDto9UXXJ5iQu5czQJ/LEJVvycF2zsSzjZE2HItFqzHmZ
rbqbUfoja994FWToRhBbAacye5IoHDMaEzq/cAOmGbVrI3pEa/YEnXlJXR+1A7LMMgTdVJwUKfnx
FW7oP98gb8CO0m8CnX5twct5EZku4a20jOunT9UDY58t6bKwSL8K/zGnpKMYEPk0hMe3lxroC1vz
nFITYxLoawQGGNiLW3jfc2NvTLTjt2/XgN1EI8K5GZoIcIsotXUCQ33kH5LmDHm0YsjkkTJbVrcN
6ugNub/O82pe95mlrgAxcsesjqLjCLwlMKLTtQCazXzRmPqBqB5jkNXO0gv9oSjoDuHxWgnH8YcH
hcv/RxGeU6dCu14aSGHb1SIqkVRtRBT7W0fg5lV86rl/XCzix4uqzF7Ew16wxJb0xhBs9JDYtiVm
fbFpB9iXEvD7yLzEMvRejKzs74cYSZTH6ZcSRYQfT1nU1CBT3+KuOypnqdp3/pAz0iy3E5Y1YT/i
7vDNu++Kq51RCyoNIOxSmUPvm2CfPfuk8PWeAo6MJdLe8Vwuqs6v7cC23U0HIFi4jz+WIj/0jFDr
/DSPCybc5tHgK7m0RVvoJ3TbpV8b9pcc8KEWersALy3Pf+mHPF2uF3edFP2ID0/3tY7OMAwLUtJ8
LwAr1Gi4GyBaujiuXM7FvPChriEj
`

	EncodedGenericAccount = `type: account
authority-id: mlpa
account-id: mlpa
display-name: mlpa
timestamp: 2023-02-08T12:51:16Z
username: mlpa
validation: certified
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcLBUgQAAQoABgUCY+OaxAAAgkkQALZjXtSmYr4lNv8Y81eaeL8uAi2zcpCDXRxkWQc01iYcW11R
iZ7PceSUs+zppCqSJa/NloqtqEeh6GozQYCme7N6UP1vUozSxHf0Ic4sYnCBXbGdC44KqGNOtXXV
XI9+oAZsgezUq1vyx+cYoX7nwJZYV41vZM3vGXftDOYohz2mnWG8nnBq+A5H7hDu4a2pha1kEO+H
k2jL5+mMyM+Pw+WB9HsuUFEuT9sXduuE98hSofCi+tRXHRlrr7tL6EcTx3pp5QB22sOr+YY+dbJX
Cf4hy7naLch8HRY2ovKDEpo+E1mKJ467J9X0HQUqo1FPxYj7MRBErV3+tumgnxBZQYCdG44xCDht
8AP/loqCNwfhEmAtKsWqW9XGLVqvMkvLoD2W7ldTxt6BuS6ZKF/pTDM09NWvQgWbxB/A0vOj+lUC
a/JKGqzfB1zJL2opFfEQO1WND36PF5nUErP/Mug3xENfGm2Y/34/1h06FuUX6El2lAARoDsy5xdL
n8dTA4JAmKY7Rz7Bfo/HytoNHQvc8ifxNbyxdUD5p2RweMMoMLeBao4xbmxlNfKOB4UeDnpFJR5T
wtdgiqsbdjorK/5qtdJXVSNf+mbkdGW6MNq579yjKjocrctjfO1Mfe8A4arXzQDn20metotrpl9s
s+3X5WuUiMdNbCiORoCAml6rT3QU
`

	EncodedGenericModelsAccountKeyPublicKeySha3 = "KbpWfalK58ixQ5MCpSgPCanRccf5XMebneu2OdKC8h0LhJmVyBiS-ZS6jfFUYtmr"
	EncodedGenericModelsAccountKey              = `type: account-key
authority-id: mlpa
public-key-sha3-384: KbpWfalK58ixQ5MCpSgPCanRccf5XMebneu2OdKC8h0LhJmVyBiS-ZS6jfFUYtmr
account-id: mlpa
name: models
since: 2022-11-29T12:47:21Z
body-length: 717
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcbBTQRWhcGAARAA3lLu9QQbSGi3vbt8QaOlOfyHearrle79X1X19CBYrSXjXmpM4/R/klyEwQDU
bO/aos8dYHqGAsxMMRZY+mRK43AF9UksCoWTZrSIC2/+S4p++FiXEDsN+mEcMHVRDXyKy9Y5eqB4
HeQHNahvn6HWN78faUzm9zGF3aD7ioJ8RleBB5RS/7gSVgIKMralclZvAc44xTa+fuQM7zznyhVx
R5QgpfQBbqhS4Upe5aP1f16ct5mJysyMRAlAmk8QZbCeKrookwZ+Mbq+3IjyX/hitW/XX4iGKZfc
2U6RuRdLSfwbqibk8m5vPby8SiF4KbFVWx2e9V8U0dFqHo0RkG0y8GXNEQ9yxGr0qDIwKIKhrI2S
G6sE9840pbYX8oJnlQSRoCL0czzLRVvUjvqwx1M/pPn0AKkL2LcPs3oL33y2rBhXqMc1eKXJxooa
yV4lbUSP0znfUM9PeVSnJ9mofB1DveV3BYZCRTIFgLnF6iSCsazgNBNupfRWFnj9vkkBGa5V4ZHD
BL6RO7wayXxnlTCYaW5KrCldPsoa6lp829R+A/FdO9qLYStZuCMo0VsP00d57wEx/Ap7M0o2ytSu
bVOcu0861i8Z8UWg/enhSbFFOYdMyHsAKeUFnwUeAo4x2ZbeVb0zl0FHF0WkziuHyTeZpdakDsnB
IoqQPSc3UhnXPU0AEQEAAQ==

AcLBUgQAAQoABgUCY4X/WQAAlX8QALdjF6zfEkHEI5pPPU3qNDrwVFDc4yL8f9eaX83u1gOA9U9n
CKkJ8KTBx8nrO9I9wkBg4On8Wh561Ix3f6PbvTxtrYNsAu9D73U3ZRtAQhHluJyVDcciBPg/Ka7B
tT/vvnA1kmsp9eukDYbzNudGyPfSf0N7ruPeokpxz3bsXjl6KW/bJ9nXGFB80ezleIqaVmZe9ayx
Gy7Tg9suFcqMc2YKFk4uzEPs9DLyrk+//no3wJnumd0qlUjaCWCWXaDW3CNj2kYvusd1iXDsQmuy
OUS9imKojUBeSh2PFBOnBHR7epPmwEMNHxIH3M3GiBQhZf6Q+JlqvHNL6uU65NaAr2B5AvVxMr2/
+fMBvu9IgjuMmMtxjlfDrfxGhphcuhuWg4hi9fqBhffTz7PVNJCATcBH1MmOqJOjt9p8w/udgw6I
rmh69r7BHFehGt/fd+4z2JUaGFp6L6LsLK/EICdseBGvCwrNjpH5MbJr63BxVEEBmKnbAwZzZ3tM
GGLYaEf5setwf6Bq29yWgmxvPklmCRmzAkDnMJlkqfValupt4QiBzi5qQkqOluHJwWDVOfnqxQiE
sneaiRzz5YhxhnaalT3U3HImBKtQH01rfDWZZI4pWLLnB28LT7WHghl1yR4H75AkKDIJWQ7s437W
GcujZx1ipo+NDTUt+eM/6xQu9amP
`

	EncodedGenericClassicModel = `type: model
authority-id: mlpa
series: 16
brand-id: mlpa
model: pc-mlpa
architecture: amd64
base: core20
grade: signed
snaps:
  -
    default-channel: latest/stable
    id: b598c8f0b2d4479a8f48a7c288dc5279
    name: pc
    type: gadget
  -
    default-channel: latest/stable
    id: 64481b02e3c644438b96f2d4e7dc3685
    name: pc-kernel
    type: kernel
  -
    default-channel: latest/stable
    id: 9a07654bbf514ec7b38136c7c659fb6d
    name: core20
    type: base
  -
    default-channel: latest/stable
    id: 5ff8522d7c7845d28262448f48579112
    name: m2cpd
    type: app
  -
    default-channel: latest/stable
    id: 7894cf6654ca48c690de86b063b7be49
    name: rabbitmq-server-snap
    type: app
store: mlpa
system-user-authority:
  - mlpa
timestamp: 2023-03-20T14:57:45Z
sign-key-sha3-384: KbpWfalK58ixQ5MCpSgPCanRccf5XMebneu2OdKC8h0LhJmVyBiS-ZS6jfFUYtmr

AcLBUgQAAQoABgUCZBh0aQAAcwoQAEm2lpQmrL/oFQwOFKte2rjJQa8T9RH5QBzzIxPjJVhvxIeC
S90/h/glSqIgp05ws7KcynDsRWh8pE3Vjzcdu/y64tt3Jn86I1tdM0F0l+KFJpp5eVqwX56N5/U/
z5BMoAjdx2QLQB6vERfWzF7oucNxW89LWSxx5XjByKc18u3p1EYEvaOdo1nRmiO78jMuEdNQ+AD4
sEHw2UUC4fxMeNxw5Y0IOVlzE4vnrFRFbNA8HePHhqe5Da1fHA4SluCSmGqWa0OkEM0LhGXQrc/9
8in5rz1qBHuBMxh354kwo/yCa8GYBrQywvOuU9qkrEVIBU2rFJzsJ9R/qcO5XBLSV8iU4r8YS7vE
Td1J+9u0kqPrUfPFxgmBsA080x916LDwJNQQXZTg0fgkTSekbosPU+EZXNg/0cZor6ry/4k+qxOZ
NTdMiynsqsBsK7nHB1vGQQd8nYVpT2wA0GZafSeRD+ImHI7E8tnD13kQdqBbHqLgvvb3NrTnY3GP
6947hHtp69nf48dGvE3/oANlQK9juBHUkX91zy97/veO41lTBvx4Y4XQvTMzQ/vsTiVx58Mec3kE
aN8apSJlc/MiVc0x6kDw1UpshpzOoVl97LJlfeWIEaLfzWxd9lb97ZVNXAAZUSOZllbKutb5k6U5
0L+rYn27LBwD3YGPkftqaZjXPin/
`

	EncodedStagingTrustedAccount = `type: account
authority-id: mlpa
account-id: mlpa
display-name: mlpa
timestamp: 2023-02-08T12:51:16Z
username: mlpa
validation: certified
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcLBUgQAAQoABgUCY+OaxAAAgkkQALZjXtSmYr4lNv8Y81eaeL8uAi2zcpCDXRxkWQc01iYcW11R
iZ7PceSUs+zppCqSJa/NloqtqEeh6GozQYCme7N6UP1vUozSxHf0Ic4sYnCBXbGdC44KqGNOtXXV
XI9+oAZsgezUq1vyx+cYoX7nwJZYV41vZM3vGXftDOYohz2mnWG8nnBq+A5H7hDu4a2pha1kEO+H
k2jL5+mMyM+Pw+WB9HsuUFEuT9sXduuE98hSofCi+tRXHRlrr7tL6EcTx3pp5QB22sOr+YY+dbJX
Cf4hy7naLch8HRY2ovKDEpo+E1mKJ467J9X0HQUqo1FPxYj7MRBErV3+tumgnxBZQYCdG44xCDht
8AP/loqCNwfhEmAtKsWqW9XGLVqvMkvLoD2W7ldTxt6BuS6ZKF/pTDM09NWvQgWbxB/A0vOj+lUC
a/JKGqzfB1zJL2opFfEQO1WND36PF5nUErP/Mug3xENfGm2Y/34/1h06FuUX6El2lAARoDsy5xdL
n8dTA4JAmKY7Rz7Bfo/HytoNHQvc8ifxNbyxdUD5p2RweMMoMLeBao4xbmxlNfKOB4UeDnpFJR5T
wtdgiqsbdjorK/5qtdJXVSNf+mbkdGW6MNq579yjKjocrctjfO1Mfe8A4arXzQDn20metotrpl9s
s+3X5WuUiMdNbCiORoCAml6rT3QU


type: account
authority-id: mlpa
account-id: knorr
display-name: knorr
timestamp: 2023-02-16T14:57:30Z
username: knorr
validation: certified
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcLBUgQAAQoABgUCY+5EWgAATUkQAJptKSqOnuUNpRxFXhot418pn5t9LNa98dNCSs+XpkMs4W/B
ZtCVi4oQi7WerOh9tuKYciNA+dtv6MJbGagQxwZ5eT+hyxPuWpizPYfi8UmlEnhU4i2xPdSm4xCP
RN2b8mkITKi2dbmVmE9cl/JSkL58irCIazp7mEKRBQki9jv/QQZ5EGVrXXASlaqlq/zZThoLc2w7
qmFJTWtH3kbMMLHQ0HdqZ4fpMs8WiZ+qwEp8G7By4UDiQjmR6ucaRqp6SWfmwTL8eNWm5QGjSVeQ
NM+8LRFp/3Sf7i9y4d+cekuA0gdc5lZ6ZrJH59AKqjIEgIswSY1st+CrveIhRpJtyRb1t9SeLTND
ozmGiY10M9HId2QA4/pIvneZBFAzTbT4eQ9NnAko4Cg78n4BPA7bwOKSWnkNrEnWWaX8SpaR45h7
SqyXvjv1FpuwLvC10/vaYisr2KZ7fivK5THl+H+stFv2UZbWnuzjpWWqW28Y50Zmxrp9NA8RkZYe
ZOJPv1IpPEU86ecIlM5MPvviBvi1g6UON5zVdfrL0h9fjmjIZnIILNw8MPV7v5MSQJxxe62iwDzF
NLVt79RwDxNrSgRetDvj/9tJnJLF0xXYCjOCPSGg8YnSlexaow5KvsyHa2SrZk9smf6QWrLxyFZg
gVO/1zdQ6xa1X4e0l3CuBQWrFXDd
`

	EncodedStagingRootAccountKey = `type: account-key
authority-id: mlpa
public-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h
account-id: mlpa
name: root
since: 2022-11-29T12:47:20Z
body-length: 717
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcbBTQRWhcGAARAAv51tX3HcHjMYIh/o6oAOy/dlrS38F8t2/fLnhzb3UaIPEqT5g8f+fAf0r307
/6ROzqQRbtf5uM8pPUwawRIpvrL5F6TFkSfKgzeKQeBEpAij+sjRPGfIPoARBbXFG4Z7VBZdZUyD
qIRnsP/adwBbCJ0iSX29AqT/veLOg8VYUEaRmUf1TsAnTttHqBQzvptz9vpSTj27fLTI3vcNCDYg
VUNMUmd3Sds0ynnjtlc5TuaJrvs4avq4tEL36JvJjfnyha1G4WXGTXTfrT1ZWGMQEJMuQZ2tfQdj
65uhf4rXLZmT2cumWp5Tr2NFsPDoCNXspcbzu8uT/19I1TL72LqsqxBpJbR0FPtkSlfeLz1mwepd
t7apWWMmZzebgPxNXRDr+PHE69vV1RpXr0e9tsirzdY5jmMoqd4Pjp5rOU5BUq5mbn4oX7CW7pZW
dgH+uFodF4g5mNxUciSAl7QVCVjdFNvpQkhIcS8o1K3BDJawIkPSYrBq5JpDHKGe4Fxtr6DPIeXh
3ekb/TK0igFeFq2Ge42Txmjk+YK80NHduYpTRRvNIGuYMEeSXKyt26LHNEWBMQZzYf8YXeAtuNg8
ejp3y3pLqfT2dUQdKA81drEMun31PoEep0P9jAYMBvYjUwKkbaOMerCqRIUGBv+zqzBDwzo049na
xJEd7t2R6nbANysAEQEAAQ==

AcLBUgQAAQoABgUCY4X/WAAAZecQAEpLDto9UXXJ5iQu5czQJ/LEJVvycF2zsSzjZE2HItFqzHmZ
rbqbUfoja994FWToRhBbAacye5IoHDMaEzq/cAOmGbVrI3pEa/YEnXlJXR+1A7LMMgTdVJwUKfnx
FW7oP98gb8CO0m8CnX5twct5EZku4a20jOunT9UDY58t6bKwSL8K/zGnpKMYEPk0hMe3lxroC1vz
nFITYxLoawQGGNiLW3jfc2NvTLTjt2/XgN1EI8K5GZoIcIsotXUCQ33kH5LmDHm0YsjkkTJbVrcN
6ugNub/O82pe95mlrgAxcsesjqLjCLwlMKLTtQCazXzRmPqBqB5jkNXO0gv9oSjoDuHxWgnH8YcH
hcv/RxGeU6dCu14aSGHb1SIqkVRtRBT7W0fg5lV86rl/XCzix4uqzF7Ew16wxJb0xhBs9JDYtiVm
fbFpB9iXEvD7yLzEMvRejKzs74cYSZTH6ZcSRYQfT1nU1CBT3+KuOypnqdp3/pAz0iy3E5Y1YT/i
7vDNu++Kq51RCyoNIOxSmUPvm2CfPfuk8PWeAo6MJdLe8Vwuqs6v7cC23U0HIFi4jz+WIj/0jFDr
/DSPCybc5tHgK7m0RVvoJ3TbpV8b9pcc8KEWersALy3Pf+mHPF2uF3edFP2ID0/3tY7OMAwLUtJ8
LwAr1Gi4GyBaujiuXM7FvPChriEj
`

	EncodedStagingGenericAccount = `type: account
authority-id: mlpa
account-id: mlpa
display-name: mlpa
timestamp: 2023-02-08T12:51:16Z
username: mlpa
validation: certified
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcLBUgQAAQoABgUCY+OaxAAAgkkQALZjXtSmYr4lNv8Y81eaeL8uAi2zcpCDXRxkWQc01iYcW11R
iZ7PceSUs+zppCqSJa/NloqtqEeh6GozQYCme7N6UP1vUozSxHf0Ic4sYnCBXbGdC44KqGNOtXXV
XI9+oAZsgezUq1vyx+cYoX7nwJZYV41vZM3vGXftDOYohz2mnWG8nnBq+A5H7hDu4a2pha1kEO+H
k2jL5+mMyM+Pw+WB9HsuUFEuT9sXduuE98hSofCi+tRXHRlrr7tL6EcTx3pp5QB22sOr+YY+dbJX
Cf4hy7naLch8HRY2ovKDEpo+E1mKJ467J9X0HQUqo1FPxYj7MRBErV3+tumgnxBZQYCdG44xCDht
8AP/loqCNwfhEmAtKsWqW9XGLVqvMkvLoD2W7ldTxt6BuS6ZKF/pTDM09NWvQgWbxB/A0vOj+lUC
a/JKGqzfB1zJL2opFfEQO1WND36PF5nUErP/Mug3xENfGm2Y/34/1h06FuUX6El2lAARoDsy5xdL
n8dTA4JAmKY7Rz7Bfo/HytoNHQvc8ifxNbyxdUD5p2RweMMoMLeBao4xbmxlNfKOB4UeDnpFJR5T
wtdgiqsbdjorK/5qtdJXVSNf+mbkdGW6MNq579yjKjocrctjfO1Mfe8A4arXzQDn20metotrpl9s
s+3X5WuUiMdNbCiORoCAml6rT3QU
`

	EncodedStagingGenericModelsAccountKey = `type: account-key
authority-id: mlpa
public-key-sha3-384: KbpWfalK58ixQ5MCpSgPCanRccf5XMebneu2OdKC8h0LhJmVyBiS-ZS6jfFUYtmr
account-id: mlpa
name: models
since: 2022-11-29T12:47:21Z
body-length: 717
sign-key-sha3-384: edGsBHOVCrchX6wCXYOWUAF81zcoGnoJ-JGwqcTylXQVKD6cCwDf3c8UM0YtFg2h

AcbBTQRWhcGAARAA3lLu9QQbSGi3vbt8QaOlOfyHearrle79X1X19CBYrSXjXmpM4/R/klyEwQDU
bO/aos8dYHqGAsxMMRZY+mRK43AF9UksCoWTZrSIC2/+S4p++FiXEDsN+mEcMHVRDXyKy9Y5eqB4
HeQHNahvn6HWN78faUzm9zGF3aD7ioJ8RleBB5RS/7gSVgIKMralclZvAc44xTa+fuQM7zznyhVx
R5QgpfQBbqhS4Upe5aP1f16ct5mJysyMRAlAmk8QZbCeKrookwZ+Mbq+3IjyX/hitW/XX4iGKZfc
2U6RuRdLSfwbqibk8m5vPby8SiF4KbFVWx2e9V8U0dFqHo0RkG0y8GXNEQ9yxGr0qDIwKIKhrI2S
G6sE9840pbYX8oJnlQSRoCL0czzLRVvUjvqwx1M/pPn0AKkL2LcPs3oL33y2rBhXqMc1eKXJxooa
yV4lbUSP0znfUM9PeVSnJ9mofB1DveV3BYZCRTIFgLnF6iSCsazgNBNupfRWFnj9vkkBGa5V4ZHD
BL6RO7wayXxnlTCYaW5KrCldPsoa6lp829R+A/FdO9qLYStZuCMo0VsP00d57wEx/Ap7M0o2ytSu
bVOcu0861i8Z8UWg/enhSbFFOYdMyHsAKeUFnwUeAo4x2ZbeVb0zl0FHF0WkziuHyTeZpdakDsnB
IoqQPSc3UhnXPU0AEQEAAQ==

AcLBUgQAAQoABgUCY4X/WQAAlX8QALdjF6zfEkHEI5pPPU3qNDrwVFDc4yL8f9eaX83u1gOA9U9n
CKkJ8KTBx8nrO9I9wkBg4On8Wh561Ix3f6PbvTxtrYNsAu9D73U3ZRtAQhHluJyVDcciBPg/Ka7B
tT/vvnA1kmsp9eukDYbzNudGyPfSf0N7ruPeokpxz3bsXjl6KW/bJ9nXGFB80ezleIqaVmZe9ayx
Gy7Tg9suFcqMc2YKFk4uzEPs9DLyrk+//no3wJnumd0qlUjaCWCWXaDW3CNj2kYvusd1iXDsQmuy
OUS9imKojUBeSh2PFBOnBHR7epPmwEMNHxIH3M3GiBQhZf6Q+JlqvHNL6uU65NaAr2B5AvVxMr2/
+fMBvu9IgjuMmMtxjlfDrfxGhphcuhuWg4hi9fqBhffTz7PVNJCATcBH1MmOqJOjt9p8w/udgw6I
rmh69r7BHFehGt/fd+4z2JUaGFp6L6LsLK/EICdseBGvCwrNjpH5MbJr63BxVEEBmKnbAwZzZ3tM
GGLYaEf5setwf6Bq29yWgmxvPklmCRmzAkDnMJlkqfValupt4QiBzi5qQkqOluHJwWDVOfnqxQiE
sneaiRzz5YhxhnaalT3U3HImBKtQH01rfDWZZI4pWLLnB28LT7WHghl1yR4H75AkKDIJWQ7s437W
GcujZx1ipo+NDTUt+eM/6xQu9amP
`

	EncodedStagingGenericClassicModel = `type: model
authority-id: mlpa
series: 16
brand-id: mlpa
model: pc-mlpa
architecture: amd64
base: core20
grade: signed
snaps:
  -
    default-channel: latest/stable
    id: b598c8f0b2d4479a8f48a7c288dc5279
    name: pc
    type: gadget
  -
    default-channel: latest/stable
    id: 64481b02e3c644438b96f2d4e7dc3685
    name: pc-kernel
    type: kernel
  -
    default-channel: latest/stable
    id: 9a07654bbf514ec7b38136c7c659fb6d
    name: core20
    type: base
  -
    default-channel: latest/stable
    id: 5ff8522d7c7845d28262448f48579112
    name: m2cpd
    type: app
  -
    default-channel: latest/stable
    id: 7894cf6654ca48c690de86b063b7be49
    name: rabbitmq-server-snap
    type: app
store: mlpa
system-user-authority:
  - mlpa
timestamp: 2023-03-20T14:57:45Z
sign-key-sha3-384: KbpWfalK58ixQ5MCpSgPCanRccf5XMebneu2OdKC8h0LhJmVyBiS-ZS6jfFUYtmr

AcLBUgQAAQoABgUCZBh0aQAAcwoQAEm2lpQmrL/oFQwOFKte2rjJQa8T9RH5QBzzIxPjJVhvxIeC
S90/h/glSqIgp05ws7KcynDsRWh8pE3Vjzcdu/y64tt3Jn86I1tdM0F0l+KFJpp5eVqwX56N5/U/
z5BMoAjdx2QLQB6vERfWzF7oucNxW89LWSxx5XjByKc18u3p1EYEvaOdo1nRmiO78jMuEdNQ+AD4
sEHw2UUC4fxMeNxw5Y0IOVlzE4vnrFRFbNA8HePHhqe5Da1fHA4SluCSmGqWa0OkEM0LhGXQrc/9
8in5rz1qBHuBMxh354kwo/yCa8GYBrQywvOuU9qkrEVIBU2rFJzsJ9R/qcO5XBLSV8iU4r8YS7vE
Td1J+9u0kqPrUfPFxgmBsA080x916LDwJNQQXZTg0fgkTSekbosPU+EZXNg/0cZor6ry/4k+qxOZ
NTdMiynsqsBsK7nHB1vGQQd8nYVpT2wA0GZafSeRD+ImHI7E8tnD13kQdqBbHqLgvvb3NrTnY3GP
6947hHtp69nf48dGvE3/oANlQK9juBHUkX91zy97/veO41lTBvx4Y4XQvTMzQ/vsTiVx58Mec3kE
aN8apSJlc/MiVc0x6kDw1UpshpzOoVl97LJlfeWIEaLfzWxd9lb97ZVNXAAZUSOZllbKutb5k6U5
0L+rYn27LBwD3YGPkftqaZjXPin/
`

	// snap ids
	ProdIdSnapd  = "7e27ae608c6f4af8b67b7daaf253315f"
	ProdIdCore   = "7198e7ece05f4b21890bb6dc9c0b84d7"
	ProdIdCore18 = "9abe90244cde44c495f86a92ff6ced91"
	ProdIdCore20 = "9a07654bbf514ec7b38136c7c659fb6d"
	ProdIdCore22 = "3ca6dede5e2f489c9eea42becf138448"

	StagingIdCore   = "7198e7ece05f4b21890bb6dc9c0b84d7"
	StagingIdSnapd  = "7e27ae608c6f4af8b67b7daaf253315f"
	StagingIdCore18 = "9abe90244cde44c495f86a92ff6ced91"
	StagingIdCore20 = "9a07654bbf514ec7b38136c7c659fb6d"
	StagingIdCore22 = "3ca6dede5e2f489c9eea42becf138448"
)
