name: Release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (for example: v2.67.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22'

    - name: Extract tag name
      id: extract_tag
      run: |
        if [ -n "${{ github.event.inputs.tag }}" ]; then
          echo "TAG_NAME=${{ github.event.inputs.tag }}" >> "$GITHUB_ENV"
        else
          echo "TAG_NAME=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
        fi

    - name: Pull dependencies
      run: |
        ./mkversion.sh
        go mod tidy
        go mod vendor

    - name: Create tarballs
      run: |
          TAG="${{ env.TAG_NAME }}"
          echo "${TAG}" > release_version

          tar --exclude-vcs --exclude=.github -caf "/tmp/snapd_${TAG}.tar.xz" .

          rm -rf "/tmp/snapd-${TAG}"
          cp -a . "/tmp/snapd-${TAG}"
          tar --exclude-vcs --exclude=.github -caf "/tmp/snapd_${TAG}.vendor.tar.xz" -C /tmp "snapd-${TAG}"

    - name: Get release ID
      id: get_release
      run: |
        RELEASE_ID=$(curl -s \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.TAG_NAME }}" \
          | jq -r .id)
        echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      run: gh release create ${{ env.TAG_NAME }}
        --title "Release ${{ env.TAG_NAME }}"
        ${{ env.RELEASE_TYPE }} --generate-notes
        /tmp/snapd_${{ env.TAG_NAME }}.tar.xz
        /tmp/snapd_${{ env.TAG_NAME }}.vendor.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
