name: Create Release Artifact

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.5'

    - name: Pull dependencies
      run: |
        go mod tidy
        go mod vendor
        ./mkversion.sh

    - name: Create tarball
      run: |
        tar cfah /tmp/snapd_${{ github.ref }}.tar .

    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: snapd_${{ github.ref }}.tar
        path: /tmp/snapd_${{ github.ref }}.tar
